### ISSUE TITLE
Trino gateway health state design

### ISSUE THREAD

**Issue by andythsu** [trinodb/trino-gateway#222]
Problem: Currently the health state of trino cluster is stored in-memory in trino-gateway. This is a problem because there can be multiple instances of trino-gateway, and their trino cluster states can be inconsistent. This can lead to displaying different information on gateway UI.

Solution: Create a DB to store health state of trino cluster for ALL instances of trino-gateway. The DB will have a table named `backend_state`, with the table schema `(name: String, is_healthy: boolean, last_update_time: timestamp)`

Each trino-gateway instance should have different `taskDelayMin`, as defined here: https://github.com/trinodb/trino-gateway/blob/9bbf62c4da2084159374eac4bacdd5592035eee4/gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ActiveClusterMonitor.java#L35 

_(Note: currently this line is not configurable, but we will create a PR to make it configurable._)

Then, once trino-gateway is up, it will get health state from the DB before checking with trino clusters at intervals of `taskDelayMin`. If the `last_update_time` is greater than X amount of time (this will also be configurable) or if `is_healthy=false`, then trino-gateway will get the health status from trino backend and store the result in DB. Otherwise, it will just use the state from the DB

If trino-gateway sees the health state is **unhealthy**, then it will maintain an in-memory storage where it will make Y tries (again, configurable) to trino backend. Trino-gateway will only treat trino backend as healthy AFTER it has Z successes (again, configurable) from the trino backend. After it reaches Z successes, trino-gateway will update the trino backend record in DB.

In the beginning, all trino backends will start with `PENDING` in DB.

**Comment by rdsarvar** [comment]
Spitballing a scenario here - 

What happens in the case that Kube/Core DNS (or anything node specific tbh) fails to resolve FQDNs for one of the N nodes? Would this result in total outage as the single node would continuously set all backends to failed in the central store?

**Comment by andythsu** [comment]
> Spitballing a scenario here -
> 
> What happens in the case that Kube/Core DNS (or anything node specific tbh) fails to resolve FQDNs for one of the N nodes? Would this result in total outage as the single node running Gateway would continuously set all backends to failed in the central store?

no, gateway will use the api provided by trino to determine trino's state. In the case where FQDNs fail, it should result in another error

**Comment by andythsu** [comment]
Please see https://lucid.app/lucidchart/1058db28-d6f7-4d35-95db-1231e295b989/edit?viewport_loc=-128%2C270%2C2003%2C1154%2C0_0&invitationId=inv_e2f1449c-560e-458d-81e2-cffc0d2b98e7 for the flow chart of this design.

>If trino-gateway sees the health state is unhealthy, then it will maintain an in-memory storage where it will make Y tries (again, configurable) to trino backend. Trino-gateway will only treat trino backend as healthy AFTER it has Z successes (again, configurable) from the trino backend. After it reaches Z successes, trino-gateway will update the trino backend record in DB.

This part is not included in the flow chart because I'm not sure if this is still relevant. We can omit this part to keep the logic simple or we can include this part to make gateway a bit more intelligent.

**Comment by andythsu** [comment]
One note: Right now the logic to fetch `RUNNING` queries and `QUEUED` queries is coupled with `healthy` state. See https://github.com/trinodb/trino-gateway/blob/b616d408c9bbb66ec88ec1b26935b63d91adb2ee/gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsJdbcMonitor.java#L85-L87 for `ClusterStatsJdbcMonitor` and https://github.com/trinodb/trino-gateway/blob/b616d408c9bbb66ec88ec1b26935b63d91adb2ee/gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java#L70-L77 for `ClusterStatsHttpMonitor`

If we are storing health state in the db that means we will need to decouple setting health from setting RUNNING/QUEUED queries

**Comment by andythsu** [comment]
Linking a relevant PR: https://github.com/trinodb/trino-gateway/pull/163

**Comment by andythsu** [comment]
Another note: once the admin deactivates the trino backend, trino-gateway should clear that trino backend's state from shared DB and its local cache.

**Comment by Chaho12** [comment]
Sounds all good except one thing. I am not so sure about creating a new table. 
What would be the reasons for not adding 2 fields to [gateway_backend](https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/migrations/gateway-ha.sql#L3-L9) table?

**Comment by andythsu** [comment]
> Sounds all good except one thing. I am not so sure about creating a new table. What would be the reasons for not adding 2 fields to [gateway_backend](https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/migrations/gateway-ha.sql#L3-L9) table?

yes we could do that

**Comment by oneonestar** [comment]
I have the same concern as @rdsarvar.
Health state should not be global unless we have some kind of quorum mechanism agree on the status of Trino.

The following happened in our production environment.
```
                 /-----> Gateway-1 -----> Trino-1
Client -> LoadBalancer-> Gateway-2 -----> Trino-1
                 \-----> Gateway-3 -(x)-> Trino-1 (due to network issue)
```

If we have a global health status in database, gateway-3 would continuously set Trino-1 to failed, but the truth is only Gateway-3 to Trino-1 failed. It will also be hard to find out which gateway updated the record.

I would rather like to have different information on gateway UI, so that I can figure out the issue on Gateway-3 quickly.

**Comment by andythsu** [comment]
I'm leaning towards @oneonestar 's way for this issue tbh. On a second thought, having the gateway check DB for trino states could be misleading. For example, if gateway cannot reach trino due to network issue but it still reports trino as healthy because it's only checking DB without actually interacting with trino. @willmostly

**Comment by Chaho12** [comment]
> I would rather like to have different information on gateway UI, so that I can figure out the issue on Gateway-3 quickly.

How would this work for different gateway servers when we login to web ui?
How about saving each gateway server status to db and show green/red buttons for each servers like below.
```
cluster(group) |                            Active                        |
   adhoc          gateway 1 (green) | gateway 2 (green) | gateway 3 (red)
```

so that admin will know which server has issue + when routing to adhoc group, it will not route to gateway 3

**Comment by oneonestar** [comment]
> How about saving each gateway server status to db and show green/red buttons for each servers like below.
That won't work well in dynamic environment such as K8S + Auto Scaling.

We can detect the problem by exposing health status to a monitoring endpoint. Use Datadog / Prometheus to monitor all gateway instances and sent alert if anything goes wrong.

**Comment by andythsu** [comment]
@oneonestar are you proposing the following:

- Each gateway instance will check trino clusters' health individually, then store the health state of each cluster locally 
- When routing, filter out unhealthy clusters by checking local health status
- Expose an endpoint to a monitoring software that alerts if anything goes wrong
    - I'm thinking we can have `/api/public/backends?state={state}`
    - for example, we can use `/api/public/backends?state=UNHEALTHY` to report unhealthy backends to monitoring software

**Comment by oneonestar** [comment]
> Each gateway instance will check trino clusters' health individually, then store the health state of each cluster locally
When routing, filter out unhealthy clusters by checking local health status
Expose an endpoint to a monitoring software that alerts if anything goes wrong

Yes.

> I'm thinking we can have /api/public/backends?state={state}
> for example, we can use /api/public/backends?state=UNHEALTHY to report unhealthy backends to monitoring software

IMO, JMX metrics and JMX endpoint should be used.

**Comment by andythsu** [comment]
> IMO, JMX metrics and JMX endpoint should be used.
Does JMX endpoint work with k8s readiness/liveness probe?

**Comment by oneonestar** [comment]
Airlift and Dropwizard support JMX. We only need to export the status to MBean.

**Comment by rdsarvar** [comment]
Sorry for commenting and disappearing. Thanks @oneonestar for diagraming the potential issue, it's definitely clearer than my example :smile:

To me, the current coupling (not the suggested design) is a blocker for production environment deployments. Which makes me lean towards having the simplest solution move forward with the option in the future to extend it.

> Health state should not be global unless we have some kind of quorum mechanism agree on the status of Trino.

+1 ^^

> @oneonestar are you proposing the following:
> 
> * Each gateway instance will check trino clusters' health individually, then store the health state of each cluster locally
> * When routing, filter out unhealthy clusters by checking local health status
> * Expose an endpoint to a monitoring software that alerts if anything goes wrong
>   
>   * I'm thinking we can have `/api/public/backends?state={state}`
>   * for example, we can use `/api/public/backends?state=UNHEALTHY` to report unhealthy backends to monitoring software

mixed with 

> Airlift and Dropwizard support JMX. We only need to export the status to MBean.


I +1 the simplicity of the above to keep health checking to be per pod; IMO the above is good enough for now as you get:

- self-healing Trino backends
- alerting on a per gateway<->backend basis (assumption: JMX metrics being ingested by something like Prometheus)
- time series historical datapoints on backend health (assumption: JMX metrics being ingested by something like Prometheus)

The only thing I would prefer personally is if we leveraged OpenMetrics so it could be scraped directly by Prometheus instead of requiring jmx_exporter 😄 

The drawback of the above is to see holistically the "per pod health for each backend" you wouldn't be able to use the UI and you'd be relying on a separate tool sitting on top of your datapoints like Grafana.

**Comment by mosabua** [comment]
I have finally read all the discussion here. Thank you all for your thoughts. Here are some of mine.

I agree that we should not move the info into the shared db without a quorum mechanism or so. That would mean you have to have at least 3 Trino Gateway servers.  Ideally we also track the status for each cluster from each Trino Gateway instance.  However, given the current simple requirement this feels like overkill.

The proposal to track status of each backend cluster in memory of each Trino Gateway instance locally is sufficient for now. Ideally we expose this in the UI .. and if the UI included with each instance as it the default deployment now you should be able to look at the UI of the individual instances and see their preceived backend status for the Trino clusters and diagnose with that. This should be sufficient for now. Over time we can maybe implement storing those states in the db in additon and then showing all Trino Gateway instances and their preceived backends in the UI, but that can wait.

I also share the wish to use OpenMetrics rather than JMX. Good thing is we are getting OpenMetrcis capability soon .. since we are moving to Airlift. But we can still use JMX in addition, if desired.. Trino itself does both as well.

**Comment by xkrogen** [comment]
> This will have to be a sticky config per session otherwise you could get into weird issues where the different Trino Gateway instances have potentially different Trino cluster statuses and queries therefore might get routed by one but not another instance.

Reading through the discussion here, the main concern I had is the split-brain problem that arises from letting each GW instance independently determine backend health, and I think this comment from @mosabua really captures my concern. I think we should work with the assumption that the GW is a truly stateless system where each instance is 1:1 replaceable by any other instance -- a sticky-routing requirement breaks this, and makes the behavior differentiated based on which backend you end up getting routed to. This seems to add extra complexity to the overall system. I am curious to hear others' opinions on this.

I see the value in letting each GW instance determine backend health, since as shared in @oneonestar 's [comment above](https://github.com/trinodb/trino-gateway/issues/222#issuecomment-2101673016), you could have a situation where GW instance 1 can't communicate to backend A, but instances 2 and 3 can. I think in such a case you actually want to consider the GW instance itself as unhealthy. A quorum-based mechanism seems to work well here, where a GW instance can consider _itself_ unhealthy if it doesn't agree with the quorum.

That all said, I think local health check determinations are still a definite improvement over no health determinations. But I would want to see us align on a roadmap here that satisfies all constraints.

**Comment by oneonestar** [comment]
> I assume the idea with multiple Trino Gateway instances is to have another load balancer in front of them that uses DNS/FQDN for load balancing.

Yes. I think having multiple Gateway instances behind a load balancer for high availability is a must for production environment.

> This will have to be a sticky config per session otherwise you could get into weird issues where the different Trino Gateway instances have potentially different Trino cluster statuses and queries therefore might get routed by one but not another instance

We don't need a sticky session if gateway is stateless. If a request itself contains all the necessary information for routing, we don't need a sticky session.

> I think we should work with the assumption that the GW is a truly stateless system where each instance is 1:1 replaceable by any other instance

I really like the idea of stateless gateway. We haven't make a consensus on this assumption yet, but I tried to keep it this way while I wrote my PR and reviews.

> I think in such a case you actually want to consider the GW instance itself as unhealthy. A quorum-based mechanism seems to work well here, where a GW instance can consider itself unhealthy if it doesn't agree with the quorum.

Yea. That should trigger an alert ASAP. However, a quorum-based mechanism implemented in Gateway to determine the health status by itself seems overkill. A JMX or OpenMetrics endpoint exporting the health info would allow almost any monitoring tools to catch that issue.


> different Trino Gateway instances have potentially different Trino cluster statuses and queries therefore might get routed by one but not another instance

The chance of that happening is very low. That should trigger an alert and let someone fix the underlying cause.

**Comment by xkrogen** [comment]
> > I think in such a case you actually want to consider the GW instance itself as unhealthy. A quorum-based mechanism seems to work well here, where a GW instance can consider itself unhealthy if it doesn't agree with the quorum.
> 
> Yea. That should trigger an alert ASAP. However, a quorum-based mechanism implemented in Gateway to determine the health status by itself seems overkill. A JMX or OpenMetrics endpoint exporting the health info would allow almost any monitoring tools to catch that issue.
> 
> > different Trino Gateway instances have potentially different Trino cluster statuses and queries therefore might get routed by one but not another instance
> 
> The chance of that happening is very low. That should trigger an alert and let someone fix the underlying cause.

I agree with you, but for the GW instance to even _know_ that it is out of sync like this requires storing the health-determination state from all GW instances. Otherwise, a single GW instance cannot differentiate between "backend is unhealthy" vs "I am unhealthy." We don't necessarily need a "true" quorum for this since it is not a critical consistency path, we can come up with a simple design using the existing MySQL backend. For example we could have a `backend_health_state` table with columns `gw_instance_uid, backend, healthy, last_updated_ts`. Each GW does an upsert based on its UID whenever it determines the health of each backend, and to determine if it is out of sync with other GWs, it checks the health status as viewed by other GW instances.

I do agree that this situation is rare and perhaps not worth designing for. We should carefully examine whether this kind of scenario really would require sticky-routing without such logic, and whether persisting/sharing healthchecks brings additional benefits.

**Comment by Chaho12** [comment]
> For example we could have a backend_health_state table with columns gw_instance_uid, backend, healthy, last_updated_ts

health meaning backend health status right? I still think about having these health state info in db, as db is a requirement and jmx metrics is not a necessarily a requirement in using gateway (highly preferred but not a necessity)

**Comment by xkrogen** [comment]
> > For example we could have a backend_health_state table with columns gw_instance_uid, backend, healthy, last_updated_ts
> 
> health meaning backend health status right? I still think about having these health state info in db, as db is a requirement and jmx metrics is not a necessarily a requirement in using gateway (highly preferred but not a necessity)

Yes, I meant "health" as in "backend health status", and I agree that these would be stored in the same DB.
