### ISSUE TITLE
Support HTTP/2 requests

### ISSUE THREAD

**Issue by JeongDaeKim** [trinodb/trino-gateway#451]
When clients send HTTP/2 requests (without `Host` headers), X-Forwarded headers will be set except `X-Forwarded-Host`, which causes making improper nextUris in a coordinator, resulting in connection failures from next client requests.

**Comment by oneonestar** [comment]
https://github.com/trinodb/trino-gateway/blob/fdb1aa025201bb3b2d4273a0456540bbdaca5c62/gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java#L287
Haven't tested yet. Change from `getHeader()` to [getServerName()](https://jakarta.ee/specifications/platform/11/apidocs/jakarta/servlet/servletrequest#getServerName()) should fix the problem. HTTP/2 uses authority instead of `Host` header.
> Returns the host name of the server to which the request was sent. It may be derived from a protocol specific mechanism, such as the Host header, or the HTTP/2 authority, or [RFC 7239](https://tools.ietf.org/html/rfc7239), otherwise the resolved server name or the server IP address.

**Comment by mosabua** [comment]
Will be part of Trino Gateway 11
